import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

class EmailNotifier:
    """
    Handles the formatting and delivery of security audit reports via SMTP.
    """
    def __init__(self, sender_email, app_password):
        self.sender_email = sender_email
        self.app_password = app_password
        self.smtp_server = "smtp.gmail.com"
        self.smtp_port = 587

    def send_report(self, receiver_email, findings, total_cost):
        """
        Constructs an HTML email report and sends it to the specified receiver.
        """
        # Initialize the email message container
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"🛡️ Azure Sentinel Scout Report - {datetime.now().strftime('%Y-%m-%d')}"
        msg["From"] = self.sender_email
        msg["To"] = receiver_email

        # Generate HTML list items for each security finding
        findings_html = "".join([f"<li style='color: #d83b01;'>❌ {f}</li>" for f in findings]) \
                        if findings else "<li>✅ No critical issues identified.</li>"
        
        # Professional HTML template for the email body
        html_content = f"""
        <html>
          <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333;">
            <h2 style="color: #0078d4;">Azure Security & Cost Audit Report</h2>
            <p>The automated scan has completed. Below is the summary for your subscription:</p>
            
            <table border="0" style="border-collapse: collapse; width: 100%; max-width: 500px; margin-bottom: 20px;">
              <tr style="background-color: #f3f2f1;">
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #0078d4;">Metric</th>
                <th style="padding: 12px; text-align: left; border-bottom: 2px solid #0078d4;">Value</th>
              </tr>
              <tr>
                <td style="padding: 12px; border-bottom: 1px solid #edebe9;">Estimated Costs (Last 30 Days)</td>
                <td style="padding: 12px; border-bottom: 1px solid #edebe9;"><b>{total_cost} EUR</b></td>
              </tr>
            </table>

            <h3 style="color: #2b2b2b;">Identified Issues & Recommendations:</h3>
            <ul style="line-height: 1.6;">{findings_html}</ul>
            
            <hr style="border: 0; border-top: 1px solid #edebe9; margin: 20px 0;" />
            <p style="font-size: 12px; color: #666;">
                This is an automated report generated by <b>Azure Sentinel Scout</b>.<br>
                Triggered via GitHub Actions CI/CD Pipeline.
            </p>
          </body>
        </html>
        """

        # Attach HTML content to the message
        msg.attach(MIMEText(html_content, 'html'))

        # Execute the SMTP delivery
        try:
            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()  # Upgrade connection to secure TLS
                server.login(self.sender_email, self.app_password)
                server.send_message(msg)
            print("[+] Success: Security report dispatched successfully.")
        except Exception as e:
            print(f"[-] Error: SMTP delivery failed: {e}")
            raise e  # Ensure the GitHub Action fails if the email cannot be sent